package com.realestate.duediligence.service.impl;

import java.time.*; import java.util.*; import org.springframework.data.domain.PageRequest; import org.springframework.stereotype.Service;
import com.realestate.duediligence.dto.*; import com.realestate.duediligence.entity.*; import com.realestate.duediligence.repository.*; import com.realestate.duediligence.service.DashboardStatsService; import com.realestate.duediligence.service.SearchHistoryService;
import lombok.RequiredArgsConstructor;

@Service @RequiredArgsConstructor
public class DashboardStatsServiceImpl implements DashboardStatsService {
 private final PropertyRepository propertyRepository; private final RiskSummaryRepository riskRepository; private final PermitRepository permitRepository; private final DocumentRepository documentRepository; private final SearchHistoryService searchHistoryService;
 public DashboardStatsResponse getDashboardStats(){ return DashboardStatsResponse.builder().totalProperties(propertyRepository.count()).reportsGenerated(riskRepository.count()).highRiskProperties(riskRepository.countByOverallRiskIgnoreCase("HIGH") + riskRepository.countByOverallRiskIgnoreCase("CRITICAL")).pendingReviews(propertyRepository.countByStatusIgnoreCase("PENDING")).build(); }
 public List<RecentSearchResponse> getRecentSearches(){ return searchHistoryService.getRecentSearches(10); }
 public List<Property> getRecentProperties(){ return propertyRepository.findAllByOrderByLastUpdatedDesc(PageRequest.of(0,5)); }
 public RiskDistributionResponse getRiskDistribution(){ return RiskDistributionResponse.builder().low(riskRepository.countByOverallRiskIgnoreCase("LOW")).medium(riskRepository.countByOverallRiskIgnoreCase("MEDIUM")).high(riskRepository.countByOverallRiskIgnoreCase("HIGH")).critical(riskRepository.countByOverallRiskIgnoreCase("CRITICAL")).build(); }
 public List<NotificationResponse> getNotifications(){ List<NotificationResponse> result=new ArrayList<>(); LocalDate today=LocalDate.now(); permitRepository.findByExpiryDateBetweenOrderByExpiryDateAsc(today,today.plusDays(30)).forEach(p->result.add(NotificationResponse.builder().type("PERMIT_EXPIRING").title("Permit expiring soon").message(p.getPermitType()+" for "+p.getProperty().getPropertyCode()+" expires on "+p.getExpiryDate()).createdAt(p.getCreatedAt()).build())); riskRepository.findAllByOrderByUpdatedAtDesc(PageRequest.of(0,10)).stream().filter(r->"HIGH".equalsIgnoreCase(r.getOverallRisk())||"CRITICAL".equalsIgnoreCase(r.getOverallRisk())).forEach(r->result.add(NotificationResponse.builder().type("HIGH_RISK").title("High-risk property identified").message(r.getProperty().getPropertyCode()+" is assessed as "+r.getOverallRisk()).createdAt(r.getUpdatedAt()).build())); documentRepository.findAllByOrderByUploadedAtDesc(PageRequest.of(0,5)).forEach(d->result.add(NotificationResponse.builder().type("DOCUMENT_UPLOADED").title("Document uploaded").message(d.getDocumentName()+" was added to "+d.getProperty().getPropertyCode()).createdAt(d.getUploadedAt()).build())); result.sort(Comparator.comparing(NotificationResponse::getCreatedAt,Comparator.nullsLast(Comparator.reverseOrder()))); return result.stream().limit(10).toList(); }
}
