import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../../services/api";
import Layout from "../../components/Layout/Layout";
import "./Profile.css";
import { LuBell, LuBookmark, LuBriefcase, LuBuilding, LuCalendar, LuCamera, LuCheck, LuChevronRight, LuCircleCheck, LuClock3, LuEye, LuFileCheck2, LuFileText, LuHeart, LuIdCard, LuLock, LuMail, LuMapPin, LuPencil, LuPhone, LuUpload, LuUserCog, LuX } from "react-icons/lu";

const ROLE_CONFIG = {
  BUYER: { label: "Buyer", jobTitle: "Property Buyer", department: "Retail Client", badgeColor: "#DBEAFE", badgeText: "#2563EB" },
  AGENT: { label: "Agent", jobTitle: "Property Agent", department: "Sales & Listings", badgeColor: "#DCFCE7", badgeText: "#16A34A" },
  LEGAL_REVIEWER: { label: "Legal Reviewer", jobTitle: "Legal Reviewer", department: "Legal & Compliance", badgeColor: "#EDE9FE", badgeText: "#7C3AED" },
  BANK: { label: "Bank", jobTitle: "Bank Representative", department: "Loan & Valuation", badgeColor: "#FEF3C7", badgeText: "#B45309" },
  ADMIN: { label: "Admin", jobTitle: "System Administrator", department: "Platform Operations", badgeColor: "#FEE2E2", badgeText: "#DC2626" },
};
const SETTINGS = [{ icon: LuUserCog, title: "Account", desc: "Update your personal details", action: "modal" }, { icon: LuBell, title: "Notifications", desc: "Manage alerts and email preferences", path: "/notifications" }, { icon: LuLock, title: "Security", desc: "Password and authentication", comingSoon: true }];
const statDefinitions = [{ key: "viewedProperties", label: "Properties Viewed", icon: LuEye, tone: "blue" }, { key: "savedProperties", label: "Saved Properties", icon: LuHeart, tone: "rose" }, { key: "reportsGenerated", label: "Due Diligence Reports", icon: LuFileCheck2, tone: "violet" }, { key: "documentsUploaded", label: "Documents Uploaded", icon: LuUpload, tone: "amber" }];
const initials = (name) => (name || "User").split(" ").filter(Boolean).map((word) => word[0]).join("").slice(0, 2).toUpperCase();
const joinDate = (value) => { const date = value && new Date(value); return date && !Number.isNaN(date.getTime()) ? date.toLocaleDateString("en-US", { month: "long", year: "numeric" }) : "Not available"; };
const relativeTime = (value) => { const date = new Date(value); if (Number.isNaN(date.getTime())) return ""; const minutes = Math.max(0, Math.floor((Date.now() - date) / 60000)); if (minutes < 60) return `${minutes || 1} min ago`; const hours = Math.floor(minutes / 60); if (hours < 24) return `${hours}h ago`; return `${Math.floor(hours / 24)}d ago`; };
const activityStyle = (type) => { const key = (type || "").toUpperCase(); if (key.includes("DOCUMENT")) return [LuFileText, "violet"]; if (key.includes("REPORT")) return [LuFileCheck2, "blue"]; if (key.includes("SAVED")) return [LuBookmark, "rose"]; if (key.includes("VIEW")) return [LuEye, "blue"]; return [LuClock3, "green"]; };

function Profile() {
  const navigate = useNavigate(); const photoInput = useRef(null); const currentUser = api.getCurrentUser();
  const roleKey = ROLE_CONFIG[currentUser.role] ? currentUser.role : "BUYER"; const role = ROLE_CONFIG[roleKey];
  const [profile, setProfile] = useState({ name: currentUser.fullName || "User", email: currentUser.email || "", phoneNumber: "", bio: "", location: "", avatarUrl: "", joinDate: null });
  const [dashboard, setDashboard] = useState({ completionPercentage: 0, viewedProperties: 0, savedProperties: 0, reportsGenerated: 0, documentsUploaded: 0, activity: [] });
  const [loading, setLoading] = useState(true); const [showModal, setShowModal] = useState(false); const [showToast, setShowToast] = useState(false); const [showAll, setShowAll] = useState(false); const [savingPhoto, setSavingPhoto] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", phoneNumber: "", bio: "", location: "" });
  const loadProfile = async () => { const [user, summary] = await Promise.all([api.getUserProfile(), api.getProfileDashboard()]); setProfile(user); setDashboard(summary); };
  useEffect(() => { if (!api.isAuthenticated()) { navigate("/login"); return; } loadProfile().catch((error) => console.error("Failed to load profile:", error)).finally(() => setLoading(false)); }, [navigate]);
  const openModal = () => { setForm({ name: profile.name || "", email: profile.email || "", phoneNumber: profile.phoneNumber || "", bio: profile.bio || "", location: profile.location || "" }); setShowModal(true); };
  const saveProfile = async () => { try { await api.updateUserProfile({ name: form.name.trim(), phoneNumber: form.phoneNumber.trim(), bio: form.bio.trim(), location: form.location.trim() }); await loadProfile(); localStorage.setItem("fullName", form.name.trim()); setShowModal(false); setShowToast(true); setTimeout(() => setShowToast(false), 2500); } catch (error) { alert(error.message || "Failed to update profile"); } };
  const uploadPhoto = (event) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!file.type.startsWith("image/") || file.size > 2 * 1024 * 1024) { alert("Choose a JPG, PNG, or other image smaller than 2MB."); return; } const reader = new FileReader(); reader.onload = async () => { try { setSavingPhoto(true); await api.updateUserProfile({ avatarUrl: reader.result }); await loadProfile(); setShowToast(true); setTimeout(() => setShowToast(false), 2500); } catch (error) { alert(error.message || "Failed to update profile photo"); } finally { setSavingPhoto(false); } }; reader.readAsDataURL(file); };
  if (loading) return <Layout title="Profile"><div className="profile-loading">Loading profile...</div></Layout>;
  const infoRows = [[LuIdCard, "Full Name", profile.name], [LuMail, "Email", profile.email], [LuPhone, "Phone", profile.phoneNumber || "Not specified"], [LuMapPin, "Location", profile.location || "Not specified"], [LuBriefcase, "Role", role.jobTitle], [LuBuilding, "Account Type", role.department]];
  const activity = showAll ? dashboard.activity : dashboard.activity.slice(0, 4);
  return <Layout title="Profile"><div className="profile-page"><input ref={photoInput} type="file" accept="image/*" hidden onChange={uploadPhoto} />
    <section className="profile-hero"><div className="profile-hero-left"><div className="profile-avatar profile-avatar-wrap">{profile.avatarUrl ? <img src={profile.avatarUrl} alt={profile.name} className="avatar-img" /> : initials(profile.name)}<button className="avatar-camera" type="button" aria-label="Change profile photo" onClick={() => photoInput.current?.click()} disabled={savingPhoto}><LuCamera /></button></div><div className="profile-hero-info"><h2>{profile.name}</h2><div className="profile-role"><LuBriefcase /><span>{role.jobTitle}</span><span className="role-badge" style={{ background: role.badgeColor, color: role.badgeText }}>{roleKey.replaceAll("_", " ")}</span></div><div className="profile-meta"><span><LuMail /> {profile.email}</span><span><LuBuilding /> {role.department}</span><span><LuCalendar /> Joined {joinDate(profile.joinDate)}</span></div></div></div><button className="edit-profile-btn" onClick={openModal}><LuPencil /> Edit Profile</button></section>
    <section className="completion-card"><div className="completion-copy"><div><h3>Profile Completeness</h3><p>Based on the information saved to your profile.</p></div><strong>{dashboard.completionPercentage}%</strong></div><div className="completion-track" aria-label={`Profile completeness: ${dashboard.completionPercentage}%`}><span style={{ width: `${dashboard.completionPercentage}%` }} /></div><div className="completion-footer"><span><b>{dashboard.completionPercentage}%</b> complete</span><button className="completion-btn" onClick={openModal}>Complete Profile <LuChevronRight /></button></div></section>
    <section className="stats-grid">{statDefinitions.map((stat) => { const Icon = stat.icon; return <article className="stat-card" key={stat.key}><div className={`stat-icon ${stat.tone}`}><Icon /></div><div><div className="stat-label">{stat.label}</div><div className="stat-value">{dashboard[stat.key] ?? 0}</div></div></article>; })}</section>
    <section className="profile-content"><div className="profile-card"><div className="card-heading"><h3 className="card-title">Personal Information</h3><button className="card-edit" onClick={openModal}><LuPencil /> Edit</button></div><div className="info-list">{infoRows.map(([Icon, label, value]) => <div className="info-row" key={label}><span className="info-icon"><Icon /></span><div><span>{label}</span><strong>{value}</strong></div></div>)}</div>{profile.bio && <div className="bio-section"><h4>Bio</h4><p>{profile.bio}</p></div>}</div><div className="profile-card"><h3 className="card-title">Account Settings</h3><div className="settings-list">{SETTINGS.map((setting) => { const Icon = setting.icon; return <button className="settings-item" key={setting.title} onClick={() => setting.action === "modal" ? openModal() : setting.path && navigate(setting.path)}><div className="settings-icon"><Icon /></div><div className="settings-text"><h4>{setting.title}{setting.comingSoon && <span>COMING SOON</span>}</h4><p>{setting.desc}</p></div><LuChevronRight className="chevron" /></button>; })}</div></div></section>
    <section className="profile-card activity-card"><div className="card-heading"><div><h3 className="card-title">Recent Activity</h3><p className="card-subtitle">Your recent account activity.</p></div>{dashboard.activity.length > 4 && <button className="view-all-btn" onClick={() => setShowAll((value) => !value)}>{showAll ? "Show less" : "View all"} <LuChevronRight /></button>}</div><div className="activity-list">{activity.length ? activity.map((item) => { const [Icon, tone] = activityStyle(item.activityType); return <div className="activity-item" key={item.id}><span className={`activity-icon ${tone}`}><Icon /></span><div className="activity-content"><h4>{(item.activityType || "Activity").replaceAll("_", " ")}</h4><p>{item.description || item.propertyCode || "Activity recorded"}</p></div><time>{relativeTime(item.createdAt)}</time></div>; }) : <p className="empty-activity">No activity has been recorded yet.</p>}</div>{dashboard.activity.length > 4 && <button className="activity-action" onClick={() => setShowAll((value) => !value)}>{showAll ? "Show Recent Activity" : "View All Activity"} <LuChevronRight /></button>}</section>
  </div>
  {showModal && <div className="modal-overlay" onClick={(event) => event.target === event.currentTarget && setShowModal(false)}><div className="modal-card"><div className="modal-header"><div><h3>Edit Profile</h3><p>Update your personal information</p></div><button className="modal-close" onClick={() => setShowModal(false)}><LuX /></button></div><div className="modal-body"><div className="avatar-edit-row"><div className="profile-avatar">{profile.avatarUrl ? <img src={profile.avatarUrl} alt={form.name} className="avatar-img" /> : initials(form.name)}</div><div><button className="btn-secondary" type="button" onClick={() => photoInput.current?.click()} disabled={savingPhoto}>{savingPhoto ? "Uploading..." : "Change photo"}</button><p>JPG or PNG, max 2MB</p></div></div><div className="form-row"><div className="form-group"><label>Full name</label><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></div><div className="form-group"><label>Role <span className="hint">(fixed)</span></label><input value={role.label} disabled readOnly /></div></div><div className="form-row"><div className="form-group"><label>Email <span className="hint">(fixed)</span></label><input type="email" value={form.email} disabled readOnly /></div><div className="form-group"><label>Phone</label><input value={form.phoneNumber} onChange={(event) => setForm({ ...form, phoneNumber: event.target.value })} /></div></div><div className="form-row"><div className="form-group"><label>Location</label><input value={form.location} onChange={(event) => setForm({ ...form, location: event.target.value })} /></div></div><div className="form-group full"><label>Bio</label><textarea placeholder="Tell us a little about yourself" value={form.bio} onChange={(event) => setForm({ ...form, bio: event.target.value })} /></div></div><div className="modal-footer"><button className="btn-secondary" onClick={() => setShowModal(false)}>Cancel</button><button className="btn-primary" onClick={saveProfile}><LuCheck /> Save changes</button></div></div></div>}
  {showToast && <div className="toast"><LuCircleCheck /> Profile updated successfully</div>}</Layout>;
}
export default Profile;
