package com.realestate.duediligence.service;

import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import com.realestate.duediligence.entity.Report;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;

@Service
public class PdfExportService {

    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("dd MMM yyyy, HH:mm");

    public byte[] generatePdf(Report report) {
        String html = buildHtml(report);

        try (ByteArrayOutputStream os = new ByteArrayOutputStream()) {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.withHtmlContent(html, null);
            builder.toStream(os);
            builder.run();
            return os.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF for report " + report.getId(), e);
        }
    }

   private String buildHtml(Report report) {

    String summary = escapeHtml(report.getExecutiveSummary());

    String riskColor = "#28a745";
    String riskLabel = "LOW";

    if (summary.toUpperCase().contains("HIGH")) {
        riskColor = "#dc3545";
        riskLabel = "HIGH";
    } else if (summary.toUpperCase().contains("MEDIUM")) {
        riskColor = "#ffc107";
        riskLabel = "MEDIUM";
    }

    StringBuilder html = new StringBuilder();

    html.append("""
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="UTF-8"/>

<style>

body{
    font-family: Arial, Helvetica, sans-serif;
    font-size:13px;
    color:#333;
    margin:35px;
}

.header{
    background:#1F4E78;
    color:white;
    padding:20px;
}

.header h1{
    margin:0;
    font-size:30px;
}

.section{
    margin-top:25px;
}

.section-title{
    background:#F2F6FA;
    color:#1F4E78;
    padding:10px;
    font-size:18px;
    font-weight:bold;
    border-left:5px solid #1F4E78;
}

.card{
    border:1px solid #DDD;
    padding:18px;
    margin-top:10px;
}

table{
    width:100%;
    border-collapse:collapse;
}

td{
    padding:8px;
    border-bottom:1px solid #EEE;
}

.label{
    width:35%;
    font-weight:bold;
}

.summary{
    margin-top:15px;
    padding:20px;
    border:1px solid #DDD;
    background:#FAFAFA;
    line-height:1.7;
}

.footer{
    margin-top:40px;
    text-align:center;
    font-size:11px;
    color:#777;
}

</style>

</head>

<body>

<div class="header">
<h1>Real Estate Due Diligence Report</h1>
<p>Professional Property Risk Assessment Report</p>
</div>

<div class="section">
<div class="section-title">Property Information</div>

<div class="card">

<table>
""");

    html.append("<tr><td class='label'>Report ID</td><td>")
            .append(report.getId())
            .append("</td></tr>");

    html.append("<tr><td class='label'>Property ID</td><td>")
            .append(report.getPropertyId())
            .append("</td></tr>");

    html.append("<tr><td class='label'>Generated On</td><td>")
            .append(report.getCreatedAt().format(DATE_FMT))
            .append("</td></tr>");

    html.append("<tr><td class='label'>Generated By</td><td>")
            .append(report.getCreatedBy())
            .append("</td></tr>");

    html.append("<tr><td class='label'>Status</td><td>")
            .append(report.getStatus())
            .append("</td></tr>");

    html.append("""
</table>

</div>
</div>

<div class="section">
<div class="section-title">Overall Risk Assessment</div>

<div class="card">
""");

    html.append("<h2 style='color:")
            .append(riskColor)
            .append(";'>")
            .append(riskLabel)
            .append("</h2>");

    html.append("""
<p>
Overall property risk calculated using legal,
environmental, ownership and financial analysis.
</p>

</div>

</div>

<div class="section">

<div class="section-title">
Executive Summary
</div>

<div class="summary">
""");

    html.append(summary);

    html.append("""
</div>

</div>

<div class="section">

<div class="section-title">
Disclaimer
</div>

<div class="card">

This report is generated automatically by the Real Estate Due Diligence System.

The findings are based on available property data,
uploaded documents and permit verification.

Professional legal review is recommended before making
investment decisions.

</div>

</div>

<div class="footer">

Generated by Real Estate Due Diligence System<br/>
© 2026 All Rights Reserved

</div>

</body>
</html>
""");

    return html.toString();
}

    private String escapeHtml(String text) {

    if (text == null) {
        return "";
    }

    return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#39;")
            .replace("\n", "<br/>");
}
}