CREATE TABLE support_tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL,

    subject VARCHAR(255) NOT NULL,

    description TEXT NOT NULL,

    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',

    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',

    assigned_admin_id INTEGER,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    resolved_at TIMESTAMP,

    CONSTRAINT fk_support_ticket_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_support_ticket_admin
        FOREIGN KEY (assigned_admin_id)
        REFERENCES users(user_id),

    CONSTRAINT chk_support_ticket_priority
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),

    CONSTRAINT chk_support_ticket_status
        CHECK (
            status IN (
                'OPEN',
                'IN_PROGRESS',
                'WAITING_FOR_USER',
                'RESOLVED',
                'CLOSED'
            )
        )
);


CREATE INDEX idx_support_tickets_user
    ON support_tickets(user_id);


CREATE INDEX idx_support_tickets_status
    ON support_tickets(status);


CREATE INDEX idx_support_tickets_priority
    ON support_tickets(priority);


CREATE INDEX idx_support_tickets_assigned_admin
    ON support_tickets(assigned_admin_id);


CREATE INDEX idx_support_tickets_created_at
    ON support_tickets(created_at DESC);


CREATE TABLE ticket_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ticket_id BIGINT NOT NULL,

    sender_id INTEGER NOT NULL,

    message TEXT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_ticket_message_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES support_tickets(ticket_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_ticket_message_sender
        FOREIGN KEY (sender_id)
        REFERENCES users(user_id)
);


CREATE INDEX idx_ticket_messages_ticket
    ON ticket_messages(ticket_id, created_at);


CREATE INDEX idx_ticket_messages_sender
    ON ticket_messages(sender_id);