ALTER TABLE users
    ADD COLUMN IF NOT EXISTS status VARCHAR(255);

UPDATE users
SET status = 'ACTIVE'
WHERE status IS NULL;

ALTER TABLE users
    ALTER COLUMN status SET DEFAULT 'ACTIVE';

ALTER TABLE users
    ALTER COLUMN status SET NOT NULL;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS profile_completed BOOLEAN;

UPDATE users
SET profile_completed = FALSE
WHERE profile_completed IS NULL;

ALTER TABLE users
    ALTER COLUMN profile_completed SET DEFAULT FALSE;

ALTER TABLE users
    ALTER COLUMN profile_completed SET NOT NULL;

CREATE TABLE role_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    requested_role VARCHAR(255) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    company_email VARCHAR(255) NOT NULL,
    license_number VARCHAR(255) NOT NULL,
    years_of_experience VARCHAR(100) NOT NULL,
    document_url VARCHAR(1000) NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    remarks VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_role_requests_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT chk_role_requests_requested_role
        CHECK (requested_role IN ('AGENT', 'LEGAL_REVIEWER', 'BANK')),
    CONSTRAINT chk_role_requests_status
        CHECK (status IN ('ACTIVE', 'PENDING', 'REJECTED'))
);

CREATE INDEX idx_role_requests_status
    ON role_requests(status);

CREATE INDEX idx_role_requests_requested_role
    ON role_requests(requested_role);

CREATE INDEX idx_role_requests_user_id
    ON role_requests(user_id);

CREATE UNIQUE INDEX uq_role_requests_pending_user
    ON role_requests(user_id)
    WHERE status = 'PENDING';
