import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { LuBuilding2, LuFileText, LuPlus, LuSend, LuWalletCards } from "react-icons/lu";
import Layout from "../../components/Layout/Layout";
import { api } from "../../services/api";
import "./AgentWorkspace.css";

const formatDate = (value) => value ? new Date(value).toLocaleDateString() : "—";

export default function AgentWorkspace({ page = "dashboard" }) {
  const navigate = useNavigate();
  const [data, setData] = useState(null); const [properties, setProperties] = useState([]); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [loading, setLoading] = useState(true); const [form, setForm] = useState(null); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); setError(""); try { if (page === "dashboard") setData(await api.getAgentDashboard()); else if (page === "transactions") setData({ transactions: await api.getAgentTransactions() }); else if (page === "buyer-requests") setData({ requests: await api.getAgentBuyerRequests() }); else if (page === "documents") setData({ documents: await api.getAgentDocuments() }); else setProperties(await api.getAgentProperties()); } catch (e) { setError(e.message || "Unable to load this workspace."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [page]);
  const visibleProperties = useMemo(() => properties, [properties]);
  const add = async (event, submitForVerification = false) => { event.preventDefault(); if (saving) return; setSaving(true); setError(""); setSuccess(""); try { const created = await api.createAgentProperty(form); if (submitForVerification) await api.submitAgentProperty(created.id); setSuccess(submitForVerification ? "Property submitted for verification." : "Draft saved successfully."); setForm(null); await load(); } catch (e) { setError(e.message || "Unable to save property."); } finally { setSaving(false); } };
  const submit = async (id) => { try { await api.submitAgentProperty(id); await load(); } catch (e) { setError(e.message); } };
  const title = page === "dashboard" ? "Agent Dashboard" : page === "transactions" ? "Transactions" : page === "buyer-requests" ? "Buyer Requests" : page === "documents" ? "Documents" : page === "due-diligence" ? "Due Diligence" : page === "tasks" ? "Tasks" : "My Properties";
  const name = api.getCurrentUser()?.fullName || "Agent";
  return <Layout title={title}><main className="agent-workspace"><header className="agent-page-header"><div><span className="agent-eyebrow">Agent workspace</span><h1>{title}</h1><p>{page === "dashboard" ? `Welcome back, ${name}. Manage your properties, documents, due diligence and buyer activity.` : "Live records for your managed properties."}</p></div>{["dashboard", "properties"].includes(page) && <button className="agent-primary-button" onClick={() => { setError(""); setSuccess(""); setForm({ propertyCode: "", address: "", city: "", state: "", propertyType: "", ownerName: "", estimatedPrice: "" }); }}><LuPlus size={18} /> Add Property</button>}</header>{success && <p className="agent-success" role="status">{success}</p>}{error && <p className="agent-error" role="alert">{error} <button onClick={load}>Retry</button></p>}{loading ? <div className="agent-loading"><span /> Loading your live workspace…</div> : page === "dashboard" ? <Dashboard data={data} navigate={navigate} /> : page === "transactions" ? <Transactions rows={data.transactions} /> : page === "buyer-requests" ? <BuyerRequests rows={data.requests} /> : page === "documents" ? <Documents rows={data.documents} /> : page === "due-diligence" || page === "tasks" ? <DueDiligence rows={visibleProperties} tasks={page === "tasks"} /> : <PropertyTable rows={visibleProperties} submit={submit} />}{form && <PropertyForm form={form} setForm={setForm} saving={saving} onClose={() => setForm(null)} onSaveDraft={add} onSubmitVerification={(event) => add(event, true)} />}</main></Layout>;
}
function Dashboard({ data, navigate }) { const stats = [["Total Properties", data.totalProperties, LuBuilding2], ["Draft Properties", data.draftProperties, LuFileText], ["Under Review", data.underReview, LuSend], ["Approved Properties", data.approvedProperties, LuBuilding2], ["Buyer Requests", data.buyerRequests, LuWalletCards], ["Properties Sold", data.propertiesSold, LuWalletCards]]; return <><section className="agent-stats-grid">{stats.map(([label, value, Icon]) => <article key={label} className="agent-stat-card"><span><Icon size={21} /></span><div><p>{label}</p><strong>{value}</strong></div></article>)}</section><section className="agent-card"><div className="agent-card-heading"><div><h2>Recent Properties</h2><p>Latest properties you are managing.</p></div><button onClick={() => navigate("/agent/properties")}>View All</button></div><PropertyTable rows={data.recentProperties} compact submit={() => navigate("/agent/properties")} /></section><section className="agent-card"><div className="agent-card-heading"><div><h2>Quick Actions</h2><p>Continue your property workflow.</p></div></div><div className="agent-quick-actions"><button onClick={() => navigate("/agent/properties")}><LuPlus /> <span><strong>Add Property</strong><small>Create a new draft</small></span></button><button onClick={() => navigate("/agent/documents")}><LuFileText /> <span><strong>Upload Documents</strong><small>Review property files</small></span></button><button onClick={() => navigate("/agent/due-diligence")}><LuSend /> <span><strong>Due Diligence</strong><small>Complete requirements</small></span></button><button onClick={() => navigate("/agent/buyer-requests")}><LuWalletCards /> <span><strong>Buyer Requests</strong><small>Review buyer interest</small></span></button></div></section></> }
function PropertyTable({ rows, submit, compact }) { if (!rows?.length) return <p className="admin-empty-row">No properties yet. Add your first property to start the due diligence process.</p>; return <div className="table-wrapper"><table className="recent-table"><thead><tr><th>Property</th><th>Location</th><th>Status</th><th>Documents</th><th>Last Updated</th>{!compact && <th>Action</th>}</tr></thead><tbody>{rows.map((p) => <tr key={p.id}><td>{p.title}</td><td>{p.location}</td><td><span className="status-badge">{p.status}</span></td><td>{p.documents}</td><td>{formatDate(p.updatedAt)}</td>{!compact && <td>{["DRAFT", "REJECTED"].includes(p.status) ? <button onClick={() => submit(p.id)}>Submit for review</button> : "—"}</td>}</tr>)}</tbody></table></div> }
function Transactions({ rows }) { if (!rows?.length) return <p className="admin-empty-row">No transactions are associated with your properties yet.</p>; return <div className="table-wrapper"><table className="recent-table"><thead><tr><th>Property</th><th>Buyer</th><th>Status</th><th>Amount</th><th>Date</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td>{r.property}</td><td>{r.buyer}</td><td>{r.status}</td><td>{r.amount}</td><td>{formatDate(r.createdAt)}</td></tr>)}</tbody></table></div> }
function BuyerRequests({ rows }) { if (!rows?.length) return <p className="admin-empty-row">No buyer requests have been submitted for your properties.</p>; return <div className="table-wrapper"><table className="recent-table"><thead><tr><th>Buyer</th><th>Property</th><th>Request Date</th><th>Status</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td>{r.buyer}</td><td>{r.property}</td><td>{formatDate(r.createdAt)}</td><td>{r.status}</td></tr>)}</tbody></table></div> }
function Documents({ rows }) { if (!rows?.length) return <p className="admin-empty-row">No documents have been uploaded for your properties.</p>; return <div className="table-wrapper"><table className="recent-table"><thead><tr><th>Document</th><th>Type</th><th>Property ID</th><th>Uploaded</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td>{r.documentName}</td><td>{r.documentType}</td><td>{r.propertyId}</td><td>{formatDate(r.uploadedAt)}</td></tr>)}</tbody></table></div> }
function DueDiligence({ rows, tasks }) { const incomplete = rows.filter((p) => p.documents === 0 || ["DRAFT", "REJECTED"].includes(p.status)); if (!rows?.length) return <p className="admin-empty-row">Create a property to begin due diligence.</p>; return <div className="table-wrapper"><table className="recent-table"><thead><tr><th>{tasks ? "Task" : "Property"}</th><th>Status</th><th>Documents</th><th>Progress</th></tr></thead><tbody>{(tasks ? incomplete : rows).map((p) => { const complete = p.documents > 0 && !["DRAFT", "REJECTED"].includes(p.status); return <tr key={p.id}><td>{tasks ? `Complete required information for ${p.title}` : p.title}</td><td>{p.status}</td><td>{p.documents}</td><td>{complete ? "100%" : p.documents > 0 ? "50%" : "0%"}</td></tr>; })}</tbody></table></div> }
function PropertyForm({ form, setForm, saving, onClose, onSaveDraft, onSubmitVerification }) { const field = (name, label, type = "text") => <label>{label}<input required type={type} min={type === "number" ? "0.01" : undefined} value={form[name]} onChange={(e) => setForm({ ...form, [name]: e.target.value })} /></label>; return <div className="role-dialog-layer"><section className="role-dialog agent-property-dialog"><header><h2>Add Property</h2><p>Save a draft or submit this property for admin verification.</p></header><form className="verification-form agent-property-form" onSubmit={onSaveDraft}>{field("propertyCode", "Property title")}{field("address", "Address")}{field("city", "City")}{field("state", "State")}{field("propertyType", "Property type")}{field("ownerName", "Owner name")}{field("estimatedPrice", "Estimated price", "number")}<footer><button type="button" onClick={onClose} disabled={saving}>Cancel</button><button type="submit" disabled={saving}>{saving ? "Saving…" : "Save Draft"}</button><button type="button" className="approve-request" onClick={onSubmitVerification} disabled={saving}>{saving ? "Submitting…" : "Submit for Verification"}</button></footer></form></section></div> }
